[package]
name = "bevy_multiplayer"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.12"
bevy_networking_turbulence = "0.12"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"

[lints]
workspace = true
