[package]
name = "bevy_chess"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.12"
bevy_networking_turbulence = "0.12"
serde = { version = "1.0", features = ["derive"] }
futures-lite = "1.13"

[target.'cfg(target_os = "macos")'.dependencies]
metal = "0.27"